### ISSUE TITLE
AttributeError: 'ConfigParser' object has no attribute 'readfp'

### ISSUE THREAD

**Issue by fteich** [SheffieldML/GPy#1036]
Hi,

i am trying to run GPy on windows 10 with python 3.12.0 and i can't get rid of the following error when loading the package:

Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import GPy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\GPy\__init__.py", line 6, in <module>
    from . import core
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\GPy\core\__init__.py", line 49, in <module>
    from .gp import GP
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\GPy\core\gp.py", line 8, in <module>
    from .. import likelihoods
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\GPy\likelihoods\__init__.py", line 25, in <module>
    from .bernoulli import Bernoulli
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\GPy\likelihoods\bernoulli.py", line 5, in <module>
    from ..util.univariate_Gaussian import std_norm_pdf, std_norm_cdf, derivLogCdfNormal, logCdfNormal
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\GPy\util\__init__.py", line 11, in <module>
    from . import linalg
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\GPy\util\linalg.py", line 11, in <module>
    from .config import config
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\GPy\util\config.py", line 28, in <module>
    config.readfp(open(default_file))
    ^^^^^^^^^^^^^
AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?

Can anyone help?

Thanks,
Fabian

**Comment by MartinBubel** [comment]
Hi @fteich 
even though we don't put a constraint on the maximum python version (which we should change), the available releases don't support python3.12 just yet.

You are getting an error because the `configparser` lib has changed in python3.12, as listed [here](https://docs.python.org/3/whatsnew/3.12.html#configparser).

If you need this asap, feel free to make a PR. Otherwise this may take a while and I am not sure if there are more issues with python3.12 compatibility that might arise over time. We are currently busy with hot-fixing for a number of issues limiting the usability of `GPy` as some parts of it have not aged too well. If there is a PR, we can easily fit it in the next release.

Best regards
Martin

**Comment by fteich** [comment]
Hi Martin,

thanks for the response. 

I got everything sorted by using Python 3.9 and numpy 1.24.4. This information might help others when working with GPy for the first time.

Cheers,
Fabian
