### ISSUE TITLE
import GPy fails with matplotlib 3.9.0

### ISSUE THREAD

**Issue by ArtemSokolov** [SheffieldML/GPy#1069]
`import GPy` produces the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/GPy/__init__.py", line 16, in <module>
    from . import plotting
  File "/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/GPy/plotting/__init__.py", line 156, in <module>
    change_plotting_library(lib)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/GPy/plotting/__init__.py", line 35, in change_plotting_library
    from .matplot_dep.plot_definitions import MatplotlibPlots
  File "/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/GPy/plotting/matplot_dep/plot_definitions.py", line 34, in <module>
    from . import defaults
  File "/workspace/.pyenv_mirror/user/current/lib/python3.10/site-packages/GPy/plotting/matplot_dep/defaults.py", line 47, in <module>
    data_2d = dict(s=35, edgecolors='none', linewidth=0., cmap=cm.get_cmap('hot'), alpha=.5)
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'
```

when running with the new matplotlib 3.9.0.

**Comment by MartinBubel** [comment]
Hi @ArtemSokolov 
thanks for reporting the issue. This is a bit strange as the official [documentation](https://matplotlib.org/stable/api/cm_api.html#matplotlib.cm.ColormapRegistry.get_cmap) of matplotlib.cm still lists that function, which seems to have been removed.

I'll dig in sometime next week. Shouldn't be too big of a fix.
