### ISSUE TITLE
Installation Error on Windows

### ISSUE THREAD

**Issue by vote539** [SheffieldML/GPy#266]
I am trying to upgade GPy because of issue #252.  I ran the following command, and got the error shown below.

```
PS C:\Users\me> pip install --upgrade https://github.com/SheffieldML/GPy/archive/master.zip

Collecting https://github.com/SheffieldML/GPy/archive/master.zip
  Downloading https://github.com/SheffieldML/GPy/archive/master.zip (1.5MB)
    100% |################################| 1.5MB 239kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Users\me\AppData\Local\Temp\pip-oikxnssj-build\setup.py", line 18, in read_to_rst
        f.write(pypandoc.convert('README.md', 'rst'))
      File "C:\WinPython\python-3.4.3.amd64\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u0292' in position 1732: character maps to <undefined>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\me\AppData\Local\Temp\pip-oikxnssj-build\setup.py", line 88, in <module>
        long_description=read_to_rst('README.md'),
      File "C:\Users\me\AppData\Local\Temp\pip-oikxnssj-build\setup.py", line 20, in read_to_rst
        return read(fname)
      File "C:\Users\me\AppData\Local\Temp\pip-oikxnssj-build\setup.py", line 11, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "C:\WinPython\python-3.4.3.amd64\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2241: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\me\AppData\Local\Temp\pip-oikxnssj-build
```

I'm running Python 3.4 on Windows 10.

Any ideas?

**Comment by mzwiessele** [comment]
Yes use the devel branch:

pip install --upgrade https://github.com/SheffieldML/GPy/archive/devel.zip

**Comment by vote539** [comment]
Well, the intallation proceeds farther.  At first it produces the dreaded "Unable to find vcvarsall.bat".  :disappointed:  After about 4 hours of fighting with different versions of Visual C++ compilers and multiple versions of Python, I got the compiler to run. :expressionless:  However, the installation is now failing with a new error. :persevere: 

```
...
    building 'GPy.kern.src.stationary_cython' extension
    creating build\temp.win32-3.4
    creating build\temp.win32-3.4\Release
    creating build\temp.win32-3.4\Release\GPy
    creating build\temp.win32-3.4\Release\GPy\kern
    creating build\temp.win32-3.4\Release\GPy\kern\src
    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Users\me\Anaconda3\lib\site-packages\numpy\core\include -I. -IC:\Users\Shane\Anaconda3\include -IC:\Users\Shane\Anaconda3\inc
lude /TcGPy/kern/src/stationary_cython.c /Fobuild\temp.win32-3.4\Release\GPy/kern/src/stationary_cython.obj -fopenmp -O3

    cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
    cl : Command line warning D9002 : ignoring unknown option '-O3'
    stationary_cython.c
    c:\users\me\anaconda3\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Usin
g deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    c:\users\me\appdata\local\temp\pip-k6j2qiqo-build\gpy\kern\src\stationary_utils.h(2) : fatal error C1083: Cannot
open include file: 'omp.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\cl.exe' failed with exit status 2
```

Obtaining and properly configuring a Visual C++ compiler that has OpenMP, and is also compatible with the very picky Python runtime, is prohibitive.

Is there a way you can make this "stationary_cython" be an optional dependency?  Old versions of GPy have installed without any fuss at all.

**Comment by vote539** [comment]
As a (hopefully temporary) workaround, I spun up a CentOS instance on EC2 and installed GPy on there from the "devel" branch.

FYI, at first I got the following error:

```
>>> import GPy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/GPy/__init__.py", line 18, in <module>
    from . import plotting
  File "/usr/lib64/python2.7/site-packages/GPy/plotting/__init__.py", line 31, in <module>
    change_plotting_library(lib)
  File "/usr/lib64/python2.7/site-packages/GPy/plotting/__init__.py", line 15, in change_plotting_library
    from .matplot_dep.plot_definitions import MatplotlibPlots
  File "/usr/lib64/python2.7/site-packages/GPy/plotting/matplot_dep/__init__.py", line 20, in <module>
    from .util import align_subplot_array, align_subplots, fewerXticks, removeRightTicks, removeUpperTicks
  File "/usr/lib64/python2.7/site-packages/GPy/plotting/matplot_dep/util.py", line 31, in <module>
    from matplotlib import pyplot as plt
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 97, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 25, in pylab_setup
    globals(),locals(),[backend_name])
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtkagg.py", line 10, in <module>
    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk.py", line 13, in <module>
    import gtk; gdk = gtk.gdk
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 64, in <module>
    _init()
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 52, in _init
    _gtk.init_check()
RuntimeError: could not open display
```

I reconnected to the server with X11 forwarding, and then the GPy import worked (finally).  Just a heads up, though, since failing to import when a display is not present is probably a bug worth fixing.

**Comment by mzwiessele** [comment]
you can change the backends in you user config ~/.config/GPy/user_config.py

In the plotting section, set library to 'none' and it will not load up the plotting!

**Comment by vote539** [comment]
Thanks for the fast response.  I also just discovered that if I upgraded matplotlib then the error went away. :satisfied:

**Comment by mzwiessele** [comment]
Could you check if the newest devel version fixes the plotting for you? Then we will close.

Thank you!

**Comment by vote539** [comment]
Hi, sorry for never getting back to you on this.  I ended up using GPy exclusively from a linux environment.
