### ISSUE TITLE
Error in test

### ISSUE THREAD

**Issue by mathDR** [SheffieldML/GPy#406]
Upon running nosetests GPy/testing on mac OSX 10.10.5 (Yosimite), All tests pass, 2 are skipped and one error.  The error comes down to the brent optimizer failing.  Anyone else see this?

Backtrace:
## ERROR: GPy.testing.likelihood_tests.TestNoiseModels.test_scale2_models(<GPy.likelihoods.student_t.StudentT object at 0x1074f1810>, array([[ 0.76308289,  7.79918792,  4.38409231],

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/danielmarthaler/GPy/GPy/testing/likelihood_tests.py", line 582, in t_laplace_fit_rbf_white
    m[name] = param_vals[param_num]
  File "/Users/danielmarthaler/GPy/GPy/core/parameterization/parameterized.py", line 307, in **setitem**
    param[:] = value
  File "/Users/danielmarthaler/GPy/GPy/core/parameterization/observable_array.py", line 71, in **setslice**
    return self.**setitem**(slice(start, stop), val)
  File "/Users/danielmarthaler/GPy/GPy/core/parameterization/observable_array.py", line 65, in **setitem**
    self.notify_observers()
  File "/Users/danielmarthaler/GPy/GPy/core/parameterization/observable.py", line 62, in notify_observers
    [callble(self, which=which) for _, _, callble in self.observers]
  File "/Users/danielmarthaler/GPy/GPy/core/parameterization/parameter_core.py", line 1031, in _pass_through_notify_observers
    self.notify_observers(which=which)
  File "/Users/danielmarthaler/GPy/GPy/core/parameterization/observable.py", line 62, in notify_observers
    [callble(self, which=which) for _, _, callble in self.observers]
  File "/Users/danielmarthaler/GPy/GPy/core/parameterization/parameter_core.py", line 1031, in _pass_through_notify_observers
    self.notify_observers(which=which)
  File "/Users/danielmarthaler/GPy/GPy/core/parameterization/observable.py", line 62, in notify_observers
    [callble(self, which=which) for _, _, callble in self.observers]
  File "/Users/danielmarthaler/GPy/GPy/core/parameterization/parameter_core.py", line 1029, in _parameters_changed_notification
    self.parameters_changed()
  File "/Users/danielmarthaler/GPy/GPy/core/gp.py", line 188, in parameters_changed
    self.posterior, self._log_marginal_likelihood, self.grad_dict = self.inference_method.inference(self.kern, self.X, self.likelihood, self.Y_normalized, self.mean_function, self.Y_metadata)
  File "/Users/danielmarthaler/GPy/GPy/inference/latent_function_inference/laplace.py", line 140, in inference
    f_hat, Ki_fhat = self.rasm_mode(K, Y, likelihood, Ki_f_init, Y_metadata=Y_metadata)
  File "/Users/danielmarthaler/GPy/GPy/inference/latent_function_inference/laplace.py", line 213, in rasm_mode
    raise ValueError("Shouldn't happen, brent optimization failing")
ValueError: Shouldn't happen, brent optimization failing

**Comment by mathDR** [comment]
Upgraded to El Capitan, installed climin and now, no error, so closing
