### ISSUE TITLE
Sparse Variational Log Gaussian Cox Process Unstable

### ISSUE THREAD

**Issue by sethnabarro** [SheffieldML/GPy#416]
Hi there,

I have been trying to fit a log-Gaussian Cox process to a large dataset (~2e4 datapoints), using an SVGP with a Poisson likelihood and Log link function. However I often encounter the error: '**NameError: name 'stop' is not defined**', which upon closer inspection relates to the gradient of  p(y|f) being undefined. I've tried with a variety of different number of inducing variables, but it still seems to occur. Any idea why this happens and how I could prevent it?

Thanks
Seth

**Comment by sethnabarro** [comment]
The full error is: 
Traceback (most recent call last):
  File "/Users/sethnabarro/er24-sa/Code/GP_joint_learning_experiment.py", line 99, in <module>
    gp.optimize()
  File "/usr/local/lib/python3.5/site-packages/GPy/core/gp.py", line 553, in optimize
    super(GP, self).optimize(optimizer, start, messages, max_iters, ipython_notebook, clear_after_finish, *_kwargs)
  File "/usr/local/lib/python3.5/site-packages/paramz/model.py", line 104, in optimize
    opt.run(start, f_fp=self._objective_grads, f=self._objective, fp=self._grads)
  File "/usr/local/lib/python3.5/site-packages/paramz/optimization/optimization.py", line 51, in run
    self.opt(x_init, *_kwargs)
  File "/usr/local/lib/python3.5/site-packages/paramz/optimization/optimization.py", line 124, in opt
    opt_result = optimize.fmin_l_bfgs_b(f_fp, x_init, maxfun=self.max_iters, maxiter=self.max_iters, *_opt_dict)
  File "/usr/local/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 193, in fmin_l_bfgs_b
    *_opts)
  File "/usr/local/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 330, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/usr/local/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 278, in func_and_grad
    f = fun(x, _args)
  File "/usr/local/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 289, in function_wrapper
    return function(_(wrapper_args + args))
  File "/usr/local/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "/usr/local/lib/python3.5/site-packages/paramz/model.py", line 270, in _objective_grads
    self.optimizer_array = x
  File "/usr/local/lib/python3.5/site-packages/paramz/parameterized.py", line 325, in __setattr__
    return object.**setattr**(self, name, val);
  File "/usr/local/lib/python3.5/site-packages/paramz/core/parameter_core.py", line 118, in optimizer_array
    self.trigger_update()
  File "/usr/local/lib/python3.5/site-packages/paramz/core/updateable.py", line 79, in trigger_update
    self._trigger_params_changed(trigger_parent)
  File "/usr/local/lib/python3.5/site-packages/paramz/core/parameter_core.py", line 128, in _trigger_params_changed
    self.notify_observers(None, None if trigger_parent else -np.inf)
  File "/usr/local/lib/python3.5/site-packages/paramz/core/observable.py", line 91, in notify_observers
    [callble(self, which=which) for _, _, callble in self.observers]
  File "/usr/local/lib/python3.5/site-packages/paramz/core/observable.py", line 91, in <listcomp>
    [callble(self, which=which) for _, _, callble in self.observers]
  File "/usr/local/lib/python3.5/site-packages/paramz/core/parameter_core.py", line 497, in _parameters_changed_notification
    self.parameters_changed()
  File "/usr/local/lib/python3.5/site-packages/GPy/core/svgp.py", line 57, in parameters_changed
    self.posterior, self._log_marginal_likelihood, self.grad_dict = self.inference_method.inference(self.q_u_mean, self.q_u_chol, self.kern, self.X, self.Z, self.likelihood, self.Y, self.mean_function, self.Y_metadata, KL_scale=1.0, batch_scale=float(self.X_all.shape[0])/float(self.X.shape[0]))
  File "/usr/local/lib/python3.5/site-packages/GPy/inference/latent_function_inference/svgp.py", line 77, in inference
    F, dF_dmu, dF_dv, dF_dthetaL = likelihood.variational_expectations(Y, mu, v, Y_metadata=Y_metadata)
  File "/usr/local/lib/python3.5/site-packages/GPy/likelihoods/likelihood.py", line 269, in variational_expectations
    stop#self.parameters_changed(restart=True)
NameError: name 'stop' is not defined

**Comment by mzwiessele** [comment]
It seems to me, that that feature is not implemented yet? @alansaul is that right?

**Comment by sethnabarro** [comment]
Perhaps I've got the terminology wrong. I've used an SVGP object with a Poisson likelihood, and used the default link function for the Poisson likelihood (log-link).

**Comment by lukerogerson** [comment]
I've also been using fitting SVGP with a Poisson likelihood, and have run into the same problem during optimization. The error is always triggered when using optimize_restarts, but only occasionally when using optimize. The models do converge, when they are working.

**Comment by ekalosak** [comment]
Stale.
