### ISSUE TITLE
multiple GPy models caching issue

### ISSUE THREAD

**Issue by bizso09** [SheffieldML/GPy#450]
Hi, I'm trying to reload a GPy model in the script. However, I'm getting this error. Is there a workaround for reloading a GPy model from file? It seems the problem is related to global references to a single model instance. I'm using GPy 1.0.9 and paramz 0.5.2 .

  File "C:\Python27\lib\site-packages\paramz\parameterized.py", line 335, in **setstate**
    self.parameters_changed()
  File "C:\Python27\lib\site-packages\GPy\models\sparse_gp_regression.py", line 65, in parameters_changed
    super(SparseGPRegression, self).parameters_changed()
  File "C:\Python27\lib\site-packages\GPy\core\sparse_gp_mpi.py", line 119, in parameters_changed
    super(SparseGP_MPI,self).parameters_changed()
  File "C:\Python27\lib\site-packages\GPy\core\sparse_gp.py", line 77, in parameters_changed
    self.posterior, self._log_marginal_likelihood, self.grad_dict = self.inference_method.inference(self.kern, self.X, self.Z, self.likelihood, self.Y, self.Y_metadata)
  File "C:\Python27\lib\site-packages\GPy\inference\latent_function_inference\var_dtc.py", line 88, in inference
    Kmm = kern.K(Z).copy()
  File "C:\Python27\lib\site-packages\GPy\kern\src\kernel_slice_operations.py", line 78, in wrap
    with _Slice_wrap(self, X, X2) as s:
  File "C:\Python27\lib\site-packages\GPy\kern\src\kernel_slice_operations.py", line 52, in __init__
    self.X = self.k._slice_X(X)
  File "C:\Python27\lib\site-packages\paramz\caching.py", line 282, in g
    return cacher(_args, *_kw)
  File "C:\Python27\lib\site-packages\paramz\caching.py", line 178, in __call__
    new_output = self.operation(_args, *_kw)
TypeError: _slice_X() takes exactly 2 arguments (1 given)`

**Comment by mzwiessele** [comment]
Could you try updating to the newest GPy and paramz, as I have been working on this and might have resolved this already.

Let me know if this problem persists, maybe you can send me the pickle then, so I can make it with it. This pickling thing was really not a bright idea, as it is super inconsistent when changing code…

**Comment by bizso09** [comment]
Thanks, I've updated, but now I can't even initialize a new model. It seems it's trying to read some cached values from the disk. Do you know where the cache is stored, so that I can delete it?

  SparseGPRegression(X, Y)
  File "C:\Python27\lib\site-packages\paramz\parameterized.py", line 54, in **call**
    self.initialize_parameter()
  File "C:\Python27\lib\site-packages\paramz\core\parameter_core.py", line 331, in initialize_parameter
    self.trigger_update()
  File "C:\Python27\lib\site-packages\paramz\core\updateable.py", line 79, in trigger_update
    self._trigger_params_changed(trigger_parent)
  File "C:\Python27\lib\site-packages\paramz\core\parameter_core.py", line 128, in _trigger_params_changed
    self.notify_observers(None, None if trigger_parent else -np.inf)
  File "C:\Python27\lib\site-packages\paramz\core\observable.py", line 91, in notify_observers
    [callble(self, which=which) for _, _, callble in self.observers]
  File "C:\Python27\lib\site-packages\paramz\core\parameter_core.py", line 498, in _parameters_changed_notification
    self.parameters_changed()
  File "C:\Python27\lib\site-packages\GPy\models\sparse_gp_regression.py", line 65, in parameters_changed
    super(SparseGPRegression, self).parameters_changed()
  File "C:\Python27\lib\site-packages\GPy\core\sparse_gp_mpi.py", line 119, in parameters_changed
    super(SparseGP_MPI,self).parameters_changed()
  File "C:\Python27\lib\site-packages\GPy\core\sparse_gp.py", line 77, in parameters_changed
    self.posterior, self._log_marginal_likelihood, self.grad_dict = self.inference_method.inference(self.kern, self.X, self.Z, self.likelihood, self.Y, self.Y_metadata)
  File "C:\Python27\lib\site-packages\GPy\inference\latent_function_inference\var_dtc.py", line 88, in inference
    Kmm = kern.K(Z).copy()
  File "C:\Python27\lib\site-packages\GPy\kern\src\kernel_slice_operations.py", line 85, in wrap
    with _Slice_wrap(self, X, X2) as s:
  File "C:\Python27\lib\site-packages\GPy\kern\src\kernel_slice_operations.py", line 54, in __init__
    self.X = self.k._slice_X(X)
  File "C:\Python27\lib\site-packages\paramz\caching.py", line 282, in g
    return cacher(_args, *_kw)
  File "C:\Python27\lib\site-packages\paramz\caching.py", line 178, in __call__
    new_output = self.operation(_args, *_kw)
TypeError: _slice_X() takes exactly 2 arguments (1 given)

**Comment by mzwiessele** [comment]
Did you update both, paramz and gpy?

**Comment by bizso09** [comment]
Yes, I uninstalled and reinstalled the latest version

**Comment by mzwiessele** [comment]
Sry, now I am confused, I hope GPy did'nt break! What shapes are X and Y? Are you allowed to give me the pickle file, so I can give it a look?

**Comment by bizso09** [comment]
In the second example, I'm not using pickle. I'm just initializing a dummy SparseGPRegression with some random data. I think the issue is the caching, i.e. it's trying to load something from the disk from the previous installation when it cached some values related to the previous model I built. Do you know where `paramz` stores its cache? I was looking at the source, but couldn't find it.

Here's the script I'm using

```
from GPy.models.sparse_gp_regression import SparseGPRegression
import numpy as np

X = np.array([[1,1],[1,1]]).reshape((2,2))
Y = np.array([[1,1]]).reshape((2,1))
SparseGPRegression(X, Y)
```

**Comment by mzwiessele** [comment]
I am not experiencing these issues. Maybe you have an old GPy/paramz installation somewhere?

``` python
In [1]: from GPy.models.sparse_gp_regression import SparseGPRegression
In [2]: import numpy as np
In [3]: 
In [3]: X = np.array([[1,1],[1,1]]).reshape((2,2))
In [4]: Y = np.array([[1,1]]).reshape((2,1))
In [5]: SparseGPRegression(X, Y)
Out[5]: <GPy.models.sparse_gp_regression.SparseGPRegression at 0x115a53a90>
```

**Comment by mzwiessele** [comment]
``` python
In [10]: paramz.__version__
Out[10]: '0.7.0'
In [11]: GPy.__version__
Out[11]: '1.5.5'
```

**Comment by bizso09** [comment]
```
from GPy.models.sparse_gp_regression import SparseGPRegression
import numpy as np
import paramz
import GPy

print paramz.__version__
print GPy.__version__
X = np.array([[1,1],[1,1]]).reshape((2,2))
Y = np.array([[1,1]]).reshape((2,1))
SparseGPRegression(X, Y)
```

```
0.7.0
1.5.5
Traceback (most recent call last):
  File "D:\Dropbox\EclipseProjects\test_data\test_sparse_gp.py", line 15, in <module>
    SparseGPRegression(X, Y)
  File "C:\Python27\lib\site-packages\paramz\parameterized.py", line 54, in __call__
    self.initialize_parameter()
  File "C:\Python27\lib\site-packages\paramz\core\parameter_core.py", line 331, in initialize_parameter
    self.trigger_update()
  File "C:\Python27\lib\site-packages\paramz\core\updateable.py", line 79, in trigger_update
    self._trigger_params_changed(trigger_parent)
  File "C:\Python27\lib\site-packages\paramz\core\parameter_core.py", line 128, in _trigger_params_changed
    self.notify_observers(None, None if trigger_parent else -np.inf)
  File "C:\Python27\lib\site-packages\paramz\core\observable.py", line 91, in notify_observers
    [callble(self, which=which) for _, _, callble in self.observers]
  File "C:\Python27\lib\site-packages\paramz\core\parameter_core.py", line 498, in _parameters_changed_notification
    self.parameters_changed()
  File "C:\Python27\lib\site-packages\GPy\models\sparse_gp_regression.py", line 65, in parameters_changed
    super(SparseGPRegression, self).parameters_changed()
  File "C:\Python27\lib\site-packages\GPy\core\sparse_gp_mpi.py", line 119, in parameters_changed
    super(SparseGP_MPI,self).parameters_changed()
  File "C:\Python27\lib\site-packages\GPy\core\sparse_gp.py", line 77, in parameters_changed
    self.posterior, self._log_marginal_likelihood, self.grad_dict = self.inference_method.inference(self.kern, self.X, self.Z, self.likelihood, self.Y, self.Y_metadata)
  File "C:\Python27\lib\site-packages\GPy\inference\latent_function_inference\var_dtc.py", line 88, in inference
    Kmm = kern.K(Z).copy()
  File "C:\Python27\lib\site-packages\GPy\kern\src\kernel_slice_operations.py", line 85, in wrap
    with _Slice_wrap(self, X, X2) as s:
  File "C:\Python27\lib\site-packages\GPy\kern\src\kernel_slice_operations.py", line 54, in __init__
    self.X = self.k._slice_X(X)
  File "C:\Python27\lib\site-packages\paramz\caching.py", line 282, in g
    return cacher(*args, **kw)
  File "C:\Python27\lib\site-packages\paramz\caching.py", line 178, in __call__
    new_output = self.operation(*args, **kw)
TypeError: _slice_X() takes exactly 2 arguments (1 given)
```

**Comment by mzwiessele** [comment]
Can you run the tests suite `GPy.tests()`?

**Comment by mzwiessele** [comment]
Oh no, I will look into it first thing tomorrow morning. I hope it is not GPy being broken! Btw, the caching is per session, so it shouldn't be the problem.

**Comment by bizso09** [comment]
Most tests are failing with the above error message. Do you think it might be possible that the caching persists somehow between sessions? In addition, if I were to load a GPy model from pickle, and then reload it, i.e. have two GPy models during a run, would that work? That's what I was doing originally.

**Comment by mzwiessele** [comment]
It must be the package setup and and old package must be lying around somewhere. I have run the tests on windows and they run fine for me. Unfortunately I cannot do more here :(

**Comment by bizso09** [comment]
I'm getting the same error on linux. I'll see if I can track it down.

**Comment by bizso09** [comment]
Hmm, been debugging... it seems KernCallsViaSlicerMeta is caching some functions to the python installation ?? I'll come back to this in a few hours.

**Comment by bizso09** [comment]
It seems the `decorator` dependency was out of date. Thanks for your help!

**Comment by bizso09** [comment]
one follow up question. I've managed to reload a GPy model from file, however, I'm operating under constrained memory resources, and I'm getting MemoryError. Is there a way I can disable caching, or are the cached valued garbage collected automatically once a reference to a GP objects is null?

**Comment by mzwiessele** [comment]
They should be garbage collected, yes.

You can turn caching off by calling m.cache.disable_caching(). If you want to never have the cache filled, you can create a model by passing initialize=False as argument to the constructor, the turn the caching off, and then initialize the model (m.initialize_parameter()).
