### ISSUE TITLE
GPRegressionGrid error

### ISSUE THREAD

**Issue by junpenglao** [SheffieldML/GPy#474]
Hi there,
I am trying to set up a GPRegressionGrid:
```python
# simple example from GPy.testing.grid_tests
X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
Y = np.random.randn(8, 1) * 100
dim = X.shape[1]

kernel = GPy.kern.RBF(input_dim=dim, variance=1, ARD=True)
m = GPy.models.GPRegressionGrid(X, Y, kernel)
```
but I kept running into the following error:
```python
Traceback (most recent call last):

  File "<ipython-input-87-8c8898850792>", line 6, in <module>
    m = GPy.models.GPRegressionGrid(X, Y, kernel)

  File "/usr/local/lib/python3.5/dist-packages/paramz/parameterized.py", line 54, in __call__
    self.initialize_parameter()

  File "/usr/local/lib/python3.5/dist-packages/paramz/core/parameter_core.py", line 331, in initialize_parameter
    self.trigger_update()

  File "/usr/local/lib/python3.5/dist-packages/paramz/core/updateable.py", line 79, in trigger_update
    self._trigger_params_changed(trigger_parent)

  File "/usr/local/lib/python3.5/dist-packages/paramz/core/parameter_core.py", line 128, in _trigger_params_changed
    self.notify_observers(None, None if trigger_parent else -np.inf)

  File "/usr/local/lib/python3.5/dist-packages/paramz/core/observable.py", line 91, in notify_observers
    [callble(self, which=which) for _, _, callble in self.observers]

  File "/usr/local/lib/python3.5/dist-packages/paramz/core/observable.py", line 91, in <listcomp>
    [callble(self, which=which) for _, _, callble in self.observers]

  File "/usr/local/lib/python3.5/dist-packages/paramz/core/parameter_core.py", line 498, in _parameters_changed_notification
    self.parameters_changed()

  File "/usr/local/lib/python3.5/dist-packages/GPy/core/gp_grid.py", line 61, in parameters_changed
    self.posterior, self._log_marginal_likelihood, self.grad_dict = self.inference_method.inference(self.kern, self.X, self.likelihood, self.Y_normalized, self.Y_metadata)

  File "/usr/local/lib/python3.5/dist-packages/GPy/inference/latent_function_inference/gaussian_grid_inference.py", line 78, in inference
    alpha_kron = self.kron_mvprod(QTs, Y)

  File "/usr/local/lib/python3.5/dist-packages/GPy/inference/latent_function_inference/gaussian_grid_inference.py", line 44, in kron_mvprod
    X = np.reshape(x, (G[d], np.round(N/G[d])), order='F')

  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)

  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 67, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)

  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

TypeError: only integer scalar arrays can be converted to a scalar index
```

Any suggestions?

**Comment by mzwiessele** [comment]
Should be fixed with the next version. Thanks for contributing!

**Comment by junpenglao** [comment]
Thanks!
