### ISSUE TITLE
Exception if a GPRegression is copied with deepcopy after a normal copy

### ISSUE THREAD

**Issue by vnmabus** [SheffieldML/GPy#583]
If a `GPRegression` object is copied using `copy.copy` and after that one tries to use `copy.deepcopy` as in the following snippet, an exception is thrown:

```

>>> import GPy
>>> import numpy as np
>>> import copy
>>> e = GPy.kern.Exponential(input_dim=1)
>>> m = GPy.models.GPRegression(np.array([[1], [2], [3]]), np.array([[4], [5], [6]]), kernel=e)
>>> copy.copy(m)
<GPy.models.gp_regression.GPRegression object at 0xb6dc72ec>
>>> copy.deepcopy(m)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/.../lib/python3.6/site-packages/paramz/core/pickleable.py", line 101, in __deepcopy__
    s.__setstate__(copy.deepcopy(self.__getstate__(), memo)) # standard copy
  File "/.../lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/.../lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/.../lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/.../lib/python3.6/copy.py", line 297, in _reconstruct
    item = deepcopy(item, memo)
  File "/.../lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/.../lib/python3.6/site-packages/paramz/core/pickleable.py", line 101, in __deepcopy__
    s.__setstate__(copy.deepcopy(self.__getstate__(), memo)) # standard copy
  File "/.../lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/.../lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/.../lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/.../lib/python3.6/site-packages/paramz/core/pickleable.py", line 101, in __deepcopy__
    s.__setstate__(copy.deepcopy(self.__getstate__(), memo)) # standard copy
  File "/.../lib/python3.6/site-packages/paramz/parameterized.py", line 346, in __setstate__
    self.parameters_changed()
  File "/.../lib/python3.6/site-packages/GPy/core/gp.py", line 255, in parameters_changed
    self.posterior, self._log_marginal_likelihood, self.grad_dict = self.inference_method.inference(self.kern, self.X, self.likelihood, self.Y_normalized, self.mean_function, self.Y_metadata)
  File "/.../lib/python3.6/site-packages/GPy/inference/latent_function_inference/exact_gaussian_inference.py", line 45, in inference
    K = kern.K(X)
  File "/.../lib/python3.6/site-packages/GPy/kern/src/kernel_slice_operations.py", line 85, in wrap
    with _Slice_wrap(self, X, X2) as s:
  File "/.../lib/python3.6/site-packages/GPy/kern/src/kernel_slice_operations.py", line 52, in __init__
    if (self.k._all_dims_active is not None) and (self.k._sliced_X == 0):
AttributeError: 'Exponential' object has no attribute '_all_dims_active'
```

This does not happen if the first copy is skipped:
```
>>> import GPy
>>> import numpy as np
>>> import copy
>>> e = GPy.kern.Exponential(input_dim=1)
>>> m = GPy.models.GPRegression(np.array([[1], [2], [3]]), np.array([[4], [5], [6]]), kernel=e)
>>> copy.deepcopy(m)
<GPy.models.gp_regression.GPRegression object at 0xb6dbb2ec>
```

**Comment by mzwiessele** [comment]
Just use the built-in copy functionality of GPy:
```python
m.copy()
```

It does make a deep copy and takes care of the caches to not be copied unnecessarily.

**Comment by vnmabus** [comment]
Unfortunately, in my real use case I have the `GPRegression` object as an attribute of a class, and that class is copied. Your solution, if I have understood correctly, would imply that I have to define the `__copy__` and `__deepcopy__` methods used by the `copy` module in each class that contains a `GPRegression` object, and call the GPy-defined copy method in the body of that method. I think that a better option is that `GPRegression` plays well with the `copy` module, and thus no extra work is required to make a class that uses it copiable.

**Comment by bela127** [comment]
This is a bug of paramz and will  hopefully be fixed with a new version of paramz featuring the above pull request: https://github.com/sods/paramz/pull/37
