### ISSUE TITLE
Space complexity of SparseGPRegression is not linear w.r.t the number of training data

### ISSUE THREAD

**Issue by emakryo** [SheffieldML/GPy#637]
I encountered the following error when I tried SparseGPRegression with relatively large training data (N ~ 100,000). It looks like space complexity of VarDTC.inference() is not linear w.r.t the number of training data, N, though I believe the complexity of DTC is linear w.r.t. N.
I think this should be fixed because VarDTC is the default inference method for SparseGPRegression.

```
Traceback (most recent call last):
  File "SGPR.py", line 67, in <module>
    main()
  File "SGPR.py", line 63, in main
    list(map(run_save, args_list))
  File "SGPR.py", line 46, in run_save
    print(seed, task, x_dim, train_size, kern, gpr(seed, task, x_dim, train_size, kern),
  File "SGPR.py", line 34, in gpr
    m = GPy.models.SparseGPRegression(xtr_, ytr_, kernel=k, num_inducing=200)
  File "/home/anasys/miniconda3/envs/default/lib/python3.6/site-packages/paramz/parameterized.py", line 53, in __call__
    self.initialize_parameter()
  File "/home/anasys/miniconda3/envs/default/lib/python3.6/site-packages/paramz/core/parameter_core.py", line 337, in initialize_parameter
    self.trigger_update()
  File "/home/anasys/miniconda3/envs/default/lib/python3.6/site-packages/paramz/core/updateable.py", line 79, in trigger_update
    self._trigger_params_changed(trigger_parent)
  File "/home/anasys/miniconda3/envs/default/lib/python3.6/site-packages/paramz/core/parameter_core.py", line 134, in _trigger_params_changed
    self.notify_observers(None, None if trigger_parent else -np.inf)
  File "/home/anasys/miniconda3/envs/default/lib/python3.6/site-packages/paramz/core/observable.py", line 91, in notify_observers
    [callble(self, which=which) for _, _, callble in self.observers]
  File "/home/anasys/miniconda3/envs/default/lib/python3.6/site-packages/paramz/core/observable.py", line 91, in <listcomp>
    [callble(self, which=which) for _, _, callble in self.observers]
  File "/home/anasys/miniconda3/envs/default/lib/python3.6/site-packages/paramz/core/parameter_core.py", line 508, in _parameters_changed_notification
    self.parameters_changed()
  File "/home/anasys/miniconda3/envs/default/lib/python3.6/site-packages/GPy/models/sparse_gp_regression.py", line 66, in parameters_changed
    super(SparseGPRegression, self).parameters_changed()
  File "/home/anasys/miniconda3/envs/default/lib/python3.6/site-packages/GPy/core/sparse_gp_mpi.py", line 122, in parameters_changed
    super(SparseGP_MPI,self).parameters_changed()
  File "/home/anasys/miniconda3/envs/default/lib/python3.6/site-packages/GPy/core/sparse_gp.py", line 80, in parameters_changed
    mean_function=self.mean_function)
  File "/home/anasys/miniconda3/envs/default/lib/python3.6/site-packages/GPy/inference/latent_function_inference/var_dtc.py", line 145, in inference
    dL_dm = -np.dot((_LBi_Lmi_psi1.T.dot(_LBi_Lmi_psi1))
MemoryError
```

**Comment by 311dada** [comment]
I met the same problem.I used the sparseGPclassification but i met the memory error and a lot of time was spent.It was so slow.So i used the SVGP  in the core.Unfortunately, the accuracy was so low.Can you solve this problem?
