### ISSUE TITLE
Heteroscedastic regression with a mean function

### ISSUE THREAD

**Issue by doccosmos** [SheffieldML/GPy#875]
GPHeteroscedasticRegression does not support a mean function:

Traceback (most recent call last):
  File "gpflare.py", line 106, in <module>
    test()
  File "gpflare.py", line 99, in test
    m = GPy.models.GPHeteroscedasticRegression(t[:, None], yp[:, None], kern, mean_function = mf)
  File "/opt/anaconda3/lib/python3.7/site-packages/paramz/parameterized.py", line 53, in __call__
    self = super(ParametersChangedMeta, self).__call__(*args, **kw)
TypeError: __init__() got an unexpected keyword argument 'mean_function'

**Comment by lawrennd** [comment]
Hi Matthew, thanks for highlighting this. Do you have time for a bit of a poke around in the code to see where this goes wrong. I don't know if it's a simple fix, but (of course) it would be amazing to have a patch if it is. neil

**Comment by doccosmos** [comment]
GPHeteroscedasticRegression.py is just a simple wrapper with some defaults.
I believe that it can easily replaced with a version where a mean function
is also one of the default options.

**Comment by lawrennd** [comment]
Would you be willing to give the edits a go and submit a pull request? I'd be very happy to do the review.
