### ISSUE TITLE
error with numpy version

### ISSUE THREAD

**Issue by KelyNorel** [SheffieldML/GPy#997]
Hi, 
please help with this error, I'm trying to do pip install GPy ==1.9.9.
It is a dependency for mogp
mogp requires python 3.7.3
Thanks in advance

Collecting GPy==1.9.9 (from mogp)
  Downloading https://files.pythonhosted.org/packages/67/95/976598f98adbfa918a480cb2d643f93fb555ca5b6c5614f76b69678114c1/GPy-1.9.9.tar.gz (995kB)
    100% |████████████████████████████████| 1.0MB 20.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-em8aoiie/numpy-1.23.4/setup.py", line 39, in <module>
        import sys
    RuntimeError: Python version >= 3.8 required.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8m02pngl/GPy/setup.py", line 192, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/home/rnorel/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/rnorel/.pyenv/versions/3.7.3/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/rnorel/.pyenv/versions/3.7.3/envs/mogp/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-em8aoiie/numpy-1.23.4/setup.py", line 39, in <module>
        import sys
    RuntimeError: Python version >= 3.8 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8m02pngl/GPy/

**Comment by MartinBubel** [comment]
I did not test it but [this](https://github.com/SheffieldML/GPy/pull/1011) PR may gonna fix your issue, considering there will be a new `GPy` version containing the above mentioned PR (if accepted at all). It probaly woll also require `mogp` to update their dependency restrictions on `GPy`.

**Comment by MartinBubel** [comment]
Will address this in #1025 and upcoming 1.13 should fix this
